<a href="https://colab.research.google.com/github/deadpool2003/PRODIGY_ML_01/blob/main/Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [12]:
dataSet=pd.read_csv('/kc_house_data.csv')
dataSet.isnull().sum()
dataSet.drop(['sqft_above'],axis='columns',inplace=True)
conv_dates=[1 if value==2014 else 0 for value in dataSet.date]
dataSet['date']=conv_dates
print(dataSet)

               id  date     price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0      7129300520     0  221900.0         3       1.00         1180      5650
1      6414100192     0  538000.0         3       2.25         2570      7242
2      5631500400     0  180000.0         2       1.00          770     10000
3      2487200875     0  604000.0         4       3.00         1960      5000
4      1954400510     0  510000.0         3       2.00         1680      8080
...           ...   ...       ...       ...        ...          ...       ...
21606   263000018     0  360000.0         3       2.50         1530      1131
21607  6600060120     0  400000.0         4       2.50         2310      5813
21608  1523300141     0  402101.0         2       0.75         1020      1350
21609   291310100     0  400000.0         3       2.50         1600      2388
21610  1523300157     0  325000.0         2       0.75         1020      1076

       floors  waterfront  view  condition  grade  sqft_basement  yr_built  \
0         1.0           0     0          3      7              0      1955
1         2.0           0     0          3      7            400      1951
2         1.0           0     0          3      6              0      1933
3         1.0           0     0          5      7            910      1965
4         1.0           0     0          3      8              0      1987
...       ...         ...   ...        ...    ...            ...       ...
21606     3.0           0     0          3      8              0      2009
21607     2.0           0     0          3      8              0      2014
21608     2.0           0     0          3      7              0      2009
21609     2.0           0     0          3      8              0      2004
21610     2.0           0     0          3      7              0      2008

       yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15
0                 0    98178  47.5112 -122.257           1340        5650
1              1991    98125  47.7210 -122.319           1690        7639
2                 0    98028  47.7379 -122.233           2720        8062
3                 0    98136  47.5208 -122.393           1360        5000
4                 0    98074  47.6168 -122.045           1800        7503
...             ...      ...      ...      ...            ...         ...
21606             0    98103  47.6993 -122.346           1530        1509
21607             0    98146  47.5107 -122.362           1830        7200
21608             0    98144  47.5944 -122.299           1020        2007
21609             0    98027  47.5345 -122.069           1410        1287
21610             0    98144  47.5941 -122.299           1020        1357

[21611 rows x 20 columns]

In [7]:
dataSet.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,0,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,0,180000.0,2,1.00,770,10000,1.0,0,0,3,6,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,0,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,0,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,0,1987,0,98074,47.6168,-122.045,1800,7503

In [8]:
dataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21611 entries, 0 to 21610
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21611 non-null  int64
 1   date           21611 non-null  int64
 2   price          21611 non-null  float64
 3   bedrooms       21611 non-null  int64
 4   bathrooms      21611 non-null  float64
 5   sqft_living    21611 non-null  int64
 6   sqft_lot       21611 non-null  int64
 7   floors         21611 non-null  float64
 8   waterfront     21611 non-null  int64
 9   view           21611 non-null  int64
 10  condition      21611 non-null  int64
 11  grade          21611 non-null  int64
 12  sqft_basement  21611 non-null  int64
 13  yr_built       21611 non-null  int64
 14  yr_renovated   21611 non-null  int64
 15  zipcode        21611 non-null  int64
 16  lat            21611 non-null  float64
 17  long           21611 non-null  float64
 18  sqft_living15  21611 non-null  int64
 19  sqft_lot15     21611 non-null  int64
dtypes: float64(5), int64(15)
memory usage: 3.3 MB

In [9]:
y=dataSet[['price']].values
x=dataSet.drop(['id','price'],axis=1).values

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [13]:
LiRe=LinearRegression()
LiRe.fit(x_train,y_train)

LinearRegression()

In [14]:
y_predict=LiRe.predict(x_test)
print(y_predict)
print(y_test)

[[392374.43865815]
 [345798.78552722]
 [814542.95660014]
 ...
 [166435.16488059]
 [744033.98318639]
 [617609.9973914 ]]
[[385000.]
 [475000.]
 [880000.]
 ...
 [212644.]
 [635000.]
 [325000.]]

In [15]:
print("The Performance of the model is :%3f"%r2_score(y_test,y_predict))

The Performance of the model is :0.699969